- students.txt
> students.txt

- students.txt
> commit_updated_students

- students.txt
- test.txt
This time i pulled the main from upstream properly.
> Cedomir Ljubic's name

- students.txt
> addXtomyname

- students.txt
> Changed the students.txt file at my name

- students.txt
> adding a cross to my name

- students.txt
> Safwane's commit

- students.txt
Add x to the name Aadhar Agarwal
> Add X to name Aadhar

- students.txt
> add a X to my name

- students.txt
> Giacomo Added X

- students.txt
> Added X to Pietro Micelli

- students.txt
Hey, I added an X next to my name !
> added X for Carlo Antonio Patti

- students.txt
> added my name (Alex Bohane)

- students.txt
I added an X at the end of my name.
> Add an X at the end of my name

- students.txt
> first commit

- students.txt
Aubry Poitevin added the cross next to his name.
> Added the x next to my name in the student.txt file.

- students.txt
Part A
Added an X to the line with my name
> GitHub Assignment 

- students.txt
Added an 'X' in front of my name.
> Added Soumyabrata Bairagi X

- students.txt
> pull request william

- students.txt
Added a cross to Clement Pottier
> clement pottier with cross

- students.txt
> Added an X - Lucien Hauchecorne

- students.txt
> PR Rafael Valente

- README.md
- numpy_questions.py
Closes https://github.com/mathurinm/github-assignment/issues/427
> fix(docs): Correct minor bugs and add instructions in the README

- students.txt
I have added the X at the end of my name Burman Dev 
Could you please update it.
> Burman Dev: Added an x at the end of the name 

- students.txt
> Added X to my name in students.txt for Part A of the assignment

- students.txt
I added X to my name, as requested
> Added X to my name

- students.txt
Added X to my name in students.txt
> Maxim Ochterbeck

- students.txt
from victorsoto branch (and not main branch)
> Victor Soto X

- students.txt
> Added Aditeya Arya
